"""EAI network rule SQL generation and application."""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from typing import Optional

from .config import ToolkitConfig, load_config
from .languages import get_enabled_plugins

logger = logging.getLogger("sfnb_multilang.network_rules")

# Hosts required by all language installations (micromamba + conda-forge)
SHARED_HOSTS = [
    {"host": "micro.mamba.pm", "port": 443,
     "purpose": "micromamba binary download",
     "required": True, "category": "shared"},
    {"host": "api.anaconda.org", "port": 443,
     "purpose": "micromamba redirect target",
     "required": True, "category": "shared"},
    {"host": "binstar-cio-packages-prod.s3.amazonaws.com", "port": 443,
     "purpose": "Anaconda S3 storage (micromamba + conda packages)",
     "required": True, "category": "shared"},
    {"host": "conda.anaconda.org", "port": 443,
     "purpose": "conda-forge package index and downloads",
     "required": True, "category": "shared"},
    {"host": "repo.anaconda.com", "port": 443,
     "purpose": "conda-forge package CDN",
     "required": True, "category": "shared"},
]


def generate_network_rule_sql(
    config: ToolkitConfig | str,
    account: str = "",
    rule_name: str = "multilang_notebook_egress",
    integration_name: str = "multilang_notebook_eai",
) -> str:
    """Generate CREATE NETWORK RULE + CREATE EXTERNAL ACCESS INTEGRATION SQL.

    Collects required hosts from shared infrastructure and all enabled
    language plugins, deduplicates, and generates the SQL.
    """
    if isinstance(config, str):
        config = load_config(config)

    plugins = get_enabled_plugins(config)

    # Collect all hosts
    all_hosts = list(SHARED_HOSTS)

    for plugin in plugins:
        plugin_hosts = plugin.get_network_hosts(config)
        for h in plugin_hosts:
            h.setdefault("category", plugin.name)
        all_hosts.extend(plugin_hosts)

    # Account-specific host
    account = account or config.network_rule.account
    if account:
        all_hosts.append({
            "host": f"{account}.snowflakecomputing.com",
            "port": 443,
            "purpose": "Snowflake account public endpoint",
            "required": True,
            "category": "snowflake",
        })

    # Deduplicate by host
    seen: set[str] = set()
    unique_hosts: list[dict] = []
    for h in all_hosts:
        if h["host"] not in seen:
            seen.add(h["host"])
            unique_hosts.append(h)

    # Sort: shared first, then snowflake, then by plugin
    category_order = {"shared": 0, "snowflake": 1}
    unique_hosts.sort(key=lambda h: (
        category_order.get(h.get("category", "plugin"), 2),
        h["host"],
    ))

    # Build SQL
    host_lines: list[str] = []
    current_category: Optional[str] = None
    for h in unique_hosts:
        cat = h.get("category", "plugin")
        if cat != current_category:
            current_category = cat
            comment = {
                "shared": "All languages: micromamba + conda-forge",
                "snowflake": "Snowflake account endpoint",
            }.get(cat)
            if comment:
                host_lines.append(f"\n    -- {comment}")
            else:
                host_lines.append(f"\n    -- {cat}")
        host_lines.append(f"    '{h['host']}'")

    host_list = ",\n".join(host_lines)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    plugin_names = ", ".join(p.display_name for p in plugins)

    sql = f"""-- Auto-generated by sfnb-multilang toolkit
-- Languages: {plugin_names}
-- Generated: {timestamp}

CREATE OR REPLACE NETWORK RULE {rule_name}
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = (
{host_list}
  );

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION {integration_name}
  ALLOWED_NETWORK_RULES = ({rule_name})
  ENABLED = true;

-- Grant usage to notebook role:
-- GRANT USAGE ON INTEGRATION {integration_name} TO ROLE <your_role>;
--
-- Then enable in Snowsight:
-- Notebook settings > External access > toggle on {integration_name}
"""
    return sql


def export_eai_sql(
    config: ToolkitConfig | str,
    output_path: str = "./eai_setup.sql",
    account: str = "",
) -> str:
    """Generate EAI SQL and write to a file.

    Returns the absolute path to the written file.
    """
    sql = generate_network_rule_sql(config, account=account)
    abs_path = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
    with open(abs_path, "w") as f:
        f.write(sql)
    logger.info("EAI SQL written to %s", abs_path)
    return abs_path


def apply_eai(
    session,
    config: ToolkitConfig | str | None = None,
    account: str = "",
    rule_name: str = "multilang_notebook_egress",
    integration_name: str = "multilang_notebook_eai",
    grant_to_role: Optional[str] = None,
    dry_run: bool = False,
    sql_export_path: str = "./eai_setup.sql",
) -> str:
    """Generate and execute EAI SQL via the Snowpark session.

    On permission failure, writes SQL to file and prints instructions.

    Returns the generated SQL string.
    """
    if isinstance(config, str):
        config = load_config(config)
    elif config is None:
        config = ToolkitConfig()

    if not account:
        try:
            result = session.sql("SELECT CURRENT_ACCOUNT()").collect()
            account = result[0][0]
        except Exception:
            pass

    sql = generate_network_rule_sql(
        config, account=account,
        rule_name=rule_name, integration_name=integration_name,
    )

    if dry_run:
        return sql

    statements = [
        s.strip() for s in sql.split(";")
        if s.strip() and not s.strip().startswith("--")
    ]

    try:
        for stmt in statements:
            logger.info("Executing: %s...", stmt[:80])
            session.sql(stmt).collect()
            logger.info("  OK")

        if grant_to_role:
            grant_sql = f"GRANT USAGE ON INTEGRATION {integration_name} TO ROLE {grant_to_role}"
            logger.info("Executing: %s", grant_sql)
            session.sql(grant_sql).collect()

        logger.info(
            "EAI created: %s\n  Network rule: %s\n"
            "  Enable in Snowsight > Notebook settings > External access",
            integration_name, rule_name,
        )
    except Exception as exc:
        error_msg = str(exc)
        logger.warning("Failed to apply EAI: %s", error_msg)
        logger.info("Writing SQL to %s for manual execution", sql_export_path)
        export_eai_sql(config, output_path=sql_export_path, account=account)
        print(sql)

    return sql


def get_stage_hosts(session) -> list[str]:
    """Query SYSTEM$ALLOWLIST() for STAGE hosts (needed for ADBC large results)."""
    result = session.sql("""
        SELECT t.value:host::VARCHAR AS host
        FROM TABLE(FLATTEN(input => PARSE_JSON(SYSTEM$ALLOWLIST()))) AS t
        WHERE t.value:type::VARCHAR = 'STAGE'
    """).collect()
    return [row[0] for row in result]
