#!/usr/bin/env python3
"""Render CRE build artifacts from a cre_profile.yaml file.

Outputs (under docker/generated/):
  - cre_extra_install.sh   — sourced by install_prebaked_r.sh during docker build
  - cre_profile.env        — shell exports for create_cre.sh / build_cre.sh
  - cre_register.sql       — CREATE OR REPLACE + GRANT template
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def _load(path: Path) -> dict:
    data = yaml.safe_load(path.read_text()) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"Invalid profile (expected mapping): {path}")
    return data


def _list(section: dict, key: str) -> list:
    raw = section.get(key) or []
    if not isinstance(raw, list):
        raise SystemExit(f"extras.{key} must be a list")
    return [str(x).strip() for x in raw if str(x).strip()]


def render(profile_path: Path, out_dir: Path) -> None:
    prof = _load(profile_path)
    cre = prof.get("cre") or {}
    sf = prof.get("snowflake") or {}
    tarballs = prof.get("tarballs") or {}
    extras = prof.get("extras") or {}

    name = str(cre.get("name", "sfnb_multilang_r"))
    image = str(cre.get("image", "sfnb-multilang-r"))
    tag = str(cre.get("tag", "v2"))
    version_label = str(cre.get("version_label", tag))
    r_version = str(cre.get("r_version", "4.5.2"))
    snowbooks_tag = str(cre.get("snowbooks_tag", "2.5.0"))
    adbc = cre.get("adbc", True)

    registry = str(sf.get("registry_url", "")).strip()
    repo_path = str(sf.get("image_repo_path", "")).strip().lstrip("/").lower()

    conda_r = _list(extras, "conda_r")
    cran = _list(extras, "cran")
    cran_mirror = str(extras.get("cran_mirror", "https://cloud.r-project.org"))
    pip_pkgs = _list(extras, "pip")

    out_dir.mkdir(parents=True, exist_ok=True)

    # --- cre_extra_install.sh (runs inside docker build, vars from install_prebaked_r.sh)
    lines = [
        "# Auto-generated by render_cre_profile.py — do not edit by hand.",
        "set -euo pipefail",
        'echo "==> CRE profile extras (from build profile)"',
    ]
    if conda_r:
        pkgs = " ".join(f'"{p}"' for p in conda_r)
        lines.append(f'echo "  conda R: {conda_r}"')
        lines.append(f'"${{MM_BIN}}" install -y -n "${{ENV_NAME}}" -c "${{CONDA_CHANNEL}}" {pkgs}')
    if cran:
        cran_vec = ", ".join(f'"{p}"' for p in cran)
        lines.append(f'echo "  CRAN: {cran}"')
        lines.append(f'"${{R_BIN}}" --vanilla -e "')
        lines.append(f"cran <- '{cran_mirror}'")
        lines.append(f"pkgs <- c({cran_vec})")
        lines.append("missing <- pkgs[!vapply(pkgs, function(p) requireNamespace(p, quietly=TRUE), logical(1))]")
        lines.append("if (length(missing)) install.packages(missing, repos=cran, quiet=TRUE)")
        lines.append('for (p in pkgs) if (!requireNamespace(p, quietly=TRUE)) stop(\"missing: \", p)')
        lines.append('message(\"OK: extra CRAN packages\")')
        lines.append('"')
    if pip_pkgs:
        specs = " ".join(f'"{p}"' for p in pip_pkgs)
        lines.append(f'echo "  pip: {pip_pkgs}"')
        lines.append('if [[ -n "${NOTEBOOK_PY:-}" ]]; then')
        lines.append(f'  "${{NOTEBOOK_PY}}" -m pip install -q --break-system-packages {specs}')
        lines.append("else")
        lines.append('  echo "WARN: NOTEBOOK_PY unset — skip profile pip extras"')
        lines.append("fi")
    if not (conda_r or cran or pip_pkgs):
        lines.append('echo "  (no extra packages in profile)"')
    (out_dir / "cre_extra_install.sh").write_text("\n".join(lines) + "\n")

    # --- cre_profile.env
    env_lines = [
        f"CRE_NAME={name}",
        f"IMAGE_TAG={image}:{tag}",
        f"CRE_IMAGE_TAG={version_label}",
        f"SNOWBOOKS_TAG={snowbooks_tag}",
        f"SFNB_R_VERSION={r_version}",
        f"SFNB_CRE_ADBC={'1' if adbc else '0'}",
    ]
    if registry:
        env_lines.append(f"REGISTRY_URL={registry}")
    if repo_path:
        env_lines.append(f"IMAGE_REPO_PATH={repo_path}")
    if tarballs.get("snowflakeR"):
        env_lines.append(f"SNOWFLAKER_TARBALL={tarballs['snowflakeR']}")
    if tarballs.get("RSnowflake"):
        env_lines.append(f"RSNOWFLAKE_TARBALL={tarballs['RSnowflake']}")
    (out_dir / "cre_profile.env").write_text("\n".join(env_lines) + "\n")

    image_path = f"/{repo_path}/{image}:{tag}" if repo_path else f"/<schema>/<repo>/{image}:{tag}"
    sql = f"""-- Generated from {profile_path.name}
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE CUSTOM RUNTIME ENVIRONMENT {name}
    IMAGE_PATH = '{image_path}'
    BASE_IMAGE_TYPE = CPU;

DESCRIBE CUSTOM RUNTIME ENVIRONMENT {name};

GRANT USAGE ON CUSTOM RUNTIME ENVIRONMENT {name} TO ROLE SYSADMIN;
-- GRANT USAGE ON CUSTOM RUNTIME ENVIRONMENT {name} TO ROLE <notebook_role>;
"""
    (out_dir / "cre_register.sql").write_text(sql)

    print(f"Wrote {out_dir}/cre_extra_install.sh")
    print(f"Wrote {out_dir}/cre_profile.env")
    print(f"Wrote {out_dir}/cre_register.sql")


def main() -> None:
    ap = argparse.ArgumentParser(description="Render CRE docker build artifacts from YAML profile")
    ap.add_argument("profile", type=Path, help="Path to cre_profile.yaml")
    ap.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "generated",
    )
    args = ap.parse_args()
    if not args.profile.is_file():
        raise SystemExit(f"Profile not found: {args.profile}")
    render(args.profile, args.out_dir)


if __name__ == "__main__":
    main()
